### ISSUE TITLE
Not managing to launch a backup from command line using HTTP Administration protocol

### ISSUE THREAD

**Issue by rjalexa** [SemanticComputing/fuseki-docker#28]
Dear friends,
I am running your 5.0.0 container image on a Linux server with the following docker compose configuration:
```
services:
  mema_fuseki:
    image: secoresearch/fuseki:5.0.0
    container_name: mema_fuseki
    ports:
      - "3030:3030"
    volumes:
      - /home/mema/fuseki-base:/fuseki-base
    environment:
      - ADMIN_PASSWORD=myverysecretpass
      - ENABLE_UPDATE=true
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPLOAD=true
      - JVM_ARGS=-Xmx8G
    restart: unless-stopped
    networks:
      - mema_network
```
and the server works well as seen:
```
mema@newisa:~/mema_docker_compose$ docker compose ps | grep secoresearch
mema_fuseki                       secoresearch/fuseki:5.0.0                         "/docker-entrypoint.…"   mema_fuseki   18 minutes ago   Up 18 minutes          0.0.0.0:3030->3030/tcp, :::3030->3030/tcp
```
I can now connect on port 3030 of this host and get the web interface working perfectly and from it I can successfully launch a backup.

But I wish to launch such backups from a shell script using the Fuseki HTTP Administration Protocol as per the page [](https://jena.apache.org/documentation/fuseki2/fuseki-server-protocol.html) and so have tried with the following command line:
`curl -u admin:myverysecretpass -X POST http://localhost:3030/$/backup/mema_v6`
but much to my surprise while looking at the logs:
`docker compose logs -f mema_fuseki`
nothing shows up.
If I issue the command:
```
curl  http://localhost:3030/$/ping
2024-07-16T13:52:56.643+00:00
```
as you can see the response is there but still nothing shows in the logs.

Can you please help me understand how to launch a backup via the command line?

What can I check? Thank you very much for your great image.
